version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=studs
    ports:
      - '5432:5432'

  admin:
    image: adminer
    depends_on:
      - db
    ports:
      - '9999:8080'
